version: '3.8'
services:
### Springboot app
  sbpostgres:
    build:
      dockerfile: dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    networks:
      - postgres

### PG database
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=productdb
    networks:
      - postgres

### PGadmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge