insert into PRODUCT (title, price) values ('Coffee - 10oz Cup 92961', 20.4);
insert into PRODUCT (title, price) values ('Cup - Translucent 7 Oz Clear', 75.47);
insert into PRODUCT (title, price) values ('Beer - Creemore', 80.62);
insert into PRODUCT (title, price) values ('Chocolate - Unsweetened', 79.52);
insert into PRODUCT (title, price) values ('Laundry - Bag Cloth', 65.6);
insert into PRODUCT (title, price) values ('Mcguinness - Blue Curacao', 36.82);
insert into PRODUCT (title, price) values ('Lemonade - Kiwi, 591 Ml', 44.28);
insert into PRODUCT (title, price) values ('Cheese - Victor Et Berthold', 49.77);
insert into PRODUCT (title, price) values ('Wine - Sogrape Mateus Rose', 59.84);
insert into PRODUCT (title, price) values ('Wine - White, Mosel Gold', 62.96);
insert into PRODUCT (title, price) values ('Island Oasis - Raspberry', 44.14);
insert into PRODUCT (title, price) values ('Sauce - Black Current, Dry Mix', 84.81);
insert into PRODUCT (title, price) values ('Crab Brie In Phyllo', 13.27);
insert into PRODUCT (title, price) values ('Chinese Foods - Plain Fried Rice', 23.33);
insert into PRODUCT (title, price) values ('Gin - Gilbeys London, Dry', 54.31);
insert into PRODUCT (title, price) values ('Grapefruit - White', 18.71);
insert into PRODUCT (title, price) values ('Clam Nectar', 14.13);
insert into PRODUCT (title, price) values ('Banana', 91.87);
insert into PRODUCT (title, price) values ('Schnappes - Peach, Walkers', 17.42);
insert into PRODUCT (title, price) values ('Lemonade - Strawberry, 591 Ml', 38.65);
insert into PRODUCT (title, price) values ('Juice - Apple, 1.36l', 13.3);
insert into PRODUCT (title, price) values ('Cornflakes', 63.08);
insert into PRODUCT (title, price) values ('Duck - Breast', 28.72);
insert into PRODUCT (title, price) values ('Steampan - Lid For Half Size', 68.42);
insert into PRODUCT (title, price) values ('Pastry - Trippleberry Muffin - Mini', 24.22);
insert into PRODUCT (title, price) values ('Lid - Translucent, 3.5 And 6 Oz', 23.87);
insert into PRODUCT (title, price) values ('Cookie - Dough Variety', 65.54);
insert into PRODUCT (title, price) values ('Liqueur - Melon', 70.6);
insert into PRODUCT (title, price) values ('Sansho Powder', 54.39);
insert into PRODUCT (title, price) values ('Cheese - Brie', 81.65);
insert into PRODUCT (title, price) values ('Quail Eggs - Canned', 84.77);
insert into PRODUCT (title, price) values ('Carbonated Water - Raspberry', 64.88);
insert into PRODUCT (title, price) values ('Soup - Campbells Mushroom', 79.43);
insert into PRODUCT (title, price) values ('C - Plus, Orange', 52.99);
insert into PRODUCT (title, price) values ('Buffalo - Tenderloin', 72.08);
insert into PRODUCT (title, price) values ('Coke - Diet, 355 Ml', 87.08);
insert into PRODUCT (title, price) values ('Soup - Campbells Bean Medley', 40.5);
insert into PRODUCT (title, price) values ('Chutney Sauce - Mango', 55.53);
insert into PRODUCT (title, price) values ('Muffin Mix - Chocolate Chip', 53.76);
insert into PRODUCT (title, price) values ('Flavouring - Raspberry', 55.03);
insert into PRODUCT (title, price) values ('Wine - Fontanafredda Barolo', 11.53);
insert into PRODUCT (title, price) values ('Chives - Fresh', 24.6);
insert into PRODUCT (title, price) values ('Toamtoes 6x7 Select', 43.59);
insert into PRODUCT (title, price) values ('Salt - Table', 90.92);
insert into PRODUCT (title, price) values ('Halibut - Steaks', 49.06);
insert into PRODUCT (title, price) values ('Pie Pecan', 47.24);
insert into PRODUCT (title, price) values ('Flower - Dish Garden', 79.42);
insert into PRODUCT (title, price) values ('Sea Bass - Whole', 46.36);
insert into PRODUCT (title, price) values ('Pepper - Green, Chili', 13.72);
insert into PRODUCT (title, price) values ('Veal - Inside Round / Top, Lean', 31.24);
insert into PRODUCT (title, price) values ('Lamb - Loin Chops', 69.15);
insert into PRODUCT (title, price) values ('Berry Brulee', 59.22);
insert into PRODUCT (title, price) values ('Tea - Darjeeling, Azzura', 25.23);
insert into PRODUCT (title, price) values ('Veal - Heart', 38.65);
insert into PRODUCT (title, price) values ('Wine - Chateauneuf Du Pape', 47.31);
insert into PRODUCT (title, price) values ('Table Cloth 72x144 White', 74.06);
insert into PRODUCT (title, price) values ('Beets', 43.89);
insert into PRODUCT (title, price) values ('Salt And Pepper Mix - White', 14.36);
insert into PRODUCT (title, price) values ('Shrimp - Baby, Warm Water', 91.03);
insert into PRODUCT (title, price) values ('Pasta - Fusili, Dry', 92.6);
insert into PRODUCT (title, price) values ('Wild Boar - Tenderloin', 79.59);
insert into PRODUCT (title, price) values ('Pork Casing', 40.01);
insert into PRODUCT (title, price) values ('Chicken - Thigh, Bone In', 88.52);
insert into PRODUCT (title, price) values ('Beer - Blue Light', 95.23);
insert into PRODUCT (title, price) values ('Bread - Rolls, Corn', 86.69);
insert into PRODUCT (title, price) values ('Huck White Towels', 68.14);
insert into PRODUCT (title, price) values ('Soup - Chicken And Wild Rice', 56.25);
insert into PRODUCT (title, price) values ('Apple - Royal Gala', 54.15);
insert into PRODUCT (title, price) values ('Peppercorns - Green', 71.3);
insert into PRODUCT (title, price) values ('Tomatillo', 72.15);
insert into PRODUCT (title, price) values ('Lamb - Whole, Fresh', 64.04);
insert into PRODUCT (title, price) values ('Grapes - Red', 89.89);
insert into PRODUCT (title, price) values ('Lettuce - Arugula', 73.61);
insert into PRODUCT (title, price) values ('Pepper - Black, Whole', 71.45);
insert into PRODUCT (title, price) values ('Cheese - Swiss Sliced', 36.14);
insert into PRODUCT (title, price) values ('Fish - Base, Bouillion', 56.66);
insert into PRODUCT (title, price) values ('Beef - Top Sirloin - Aaa', 29.77);
insert into PRODUCT (title, price) values ('Crackers - Melba Toast', 14.44);
insert into PRODUCT (title, price) values ('Chick Peas - Canned', 70.45);
insert into PRODUCT (title, price) values ('Pepper - Green, Chili', 11.31);
insert into PRODUCT (title, price) values ('Cookies Almond Hazelnut', 95.16);
insert into PRODUCT (title, price) values ('Chef Hat 25cm', 92.83);
insert into PRODUCT (title, price) values ('Napkin - Dinner, White', 48.3);
insert into PRODUCT (title, price) values ('Otomegusa Dashi Konbu', 48.41);
insert into PRODUCT (title, price) values ('Potatoes - Idaho 100 Count', 27.55);
insert into PRODUCT (title, price) values ('Sponge Cake Mix - Chocolate', 83.2);
insert into PRODUCT (title, price) values ('Broccoli - Fresh', 96.82);
insert into PRODUCT (title, price) values ('Juice - Pineapple, 341 Ml', 34.81);
insert into PRODUCT (title, price) values ('Tea - Apple Green Tea', 97.41);
insert into PRODUCT (title, price) values ('Pepper - Black, Crushed', 35.25);
insert into PRODUCT (title, price) values ('Pancetta', 70.42);
insert into PRODUCT (title, price) values ('Mountain Dew', 91.2);
insert into PRODUCT (title, price) values ('Boogies', 24.52);
insert into PRODUCT (title, price) values ('Beer - Creemore', 31.63);
insert into PRODUCT (title, price) values ('Apple - Northern Spy', 11.34);
insert into PRODUCT (title, price) values ('Sobe - Liz Blizz', 62.57);
insert into PRODUCT (title, price) values ('Swiss Chard - Red', 62.16);
insert into PRODUCT (title, price) values ('Dried Figs', 45.03);
insert into PRODUCT (title, price) values ('Spice - Onion Powder Granulated', 33.19);
insert into PRODUCT (title, price) values ('Club Soda - Schweppes, 355 Ml', 86.76);
insert into PRODUCT (title, price) values ('Chocolate - Semi Sweet', 96.36);
insert into PRODUCT (title, price) values ('Beans - Wax', 93.39);
insert into PRODUCT (title, price) values ('Butter - Salted, Micro', 47.68);
insert into PRODUCT (title, price) values ('Milk - Chocolate 500ml', 82.11);
insert into PRODUCT (title, price) values ('Godiva White Chocolate', 27.63);
insert into PRODUCT (title, price) values ('Bacardi Breezer - Tropical', 31.38);
insert into PRODUCT (title, price) values ('Mushroom - Chantrelle, Fresh', 82.8);
insert into PRODUCT (title, price) values ('Bagel - Plain', 28.26);
insert into PRODUCT (title, price) values ('Veal - Provimi Inside', 72.96);
insert into PRODUCT (title, price) values ('Sauce - Hp', 58.17);
insert into PRODUCT (title, price) values ('Jagermeister', 91.53);
insert into PRODUCT (title, price) values ('Couscous', 99.03);
insert into PRODUCT (title, price) values ('Tomato - Plum With Basil', 85.4);
insert into PRODUCT (title, price) values ('Spaghetti Squash', 28.51);
insert into PRODUCT (title, price) values ('Chick Peas - Canned', 46.93);
insert into PRODUCT (title, price) values ('Dates', 50.82);
insert into PRODUCT (title, price) values ('Chambord Royal', 56.94);
insert into PRODUCT (title, price) values ('Pastry - Apple Large', 31.44);
insert into PRODUCT (title, price) values ('Veal - Inside, Choice', 79.21);
insert into PRODUCT (title, price) values ('Wine - Niagara Peninsula Vqa', 37.98);
insert into PRODUCT (title, price) values ('Curry Paste - Green Masala', 48.61);
insert into PRODUCT (title, price) values ('Table Cloth 72x144 White', 35.87);
insert into PRODUCT (title, price) values ('Soup Campbells - Italian Wedding', 56.28);
insert into PRODUCT (title, price) values ('Pastry - Butterscotch Baked', 33.2);
insert into PRODUCT (title, price) values ('Tea - Grapefruit Green Tea', 39.51);
insert into PRODUCT (title, price) values ('Sausage - Breakfast', 84.65);
insert into PRODUCT (title, price) values ('Quail - Jumbo Boneless', 81.68);
insert into PRODUCT (title, price) values ('Pastry - Butterscotch Baked', 77.25);
insert into PRODUCT (title, price) values ('Gelatine Leaves - Bulk', 81.1);
insert into PRODUCT (title, price) values ('Sauce - Gravy, Au Jus, Mix', 24.38);
insert into PRODUCT (title, price) values ('Energy Drink - Franks Original', 41.22);
insert into PRODUCT (title, price) values ('Filter - Coffee', 70.7);
insert into PRODUCT (title, price) values ('Beer - Labatt Blue', 41.89);
insert into PRODUCT (title, price) values ('Lumpfish Black', 79.03);
insert into PRODUCT (title, price) values ('Garam Marsala', 11.36);
insert into PRODUCT (title, price) values ('Asparagus - Frozen', 24.48);
insert into PRODUCT (title, price) values ('Snapple Lemon Tea', 67.83);
insert into PRODUCT (title, price) values ('Cognac - Courvaisier', 53.68);
insert into PRODUCT (title, price) values ('Worcestershire Sauce', 44.15);
insert into PRODUCT (title, price) values ('Paste - Black Olive', 24.05);
insert into PRODUCT (title, price) values ('Bread - Rolls, Corn', 45.74);
insert into PRODUCT (title, price) values ('Saskatoon Berries - Frozen', 63.18);
insert into PRODUCT (title, price) values ('Quail - Whole, Boneless', 47.1);
insert into PRODUCT (title, price) values ('Pork - Tenderloin, Frozen', 85.01);
insert into PRODUCT (title, price) values ('Pasta - Elbows, Macaroni, Dry', 91.92);
insert into PRODUCT (title, price) values ('Wine - White, Concha Y Toro', 30.19);
insert into PRODUCT (title, price) values ('Wine - Vineland Estate Semi - Dry', 19.86);
insert into PRODUCT (title, price) values ('Cheese - Boursin, Garlic / Herbs', 58.72);
insert into PRODUCT (title, price) values ('Schnappes Peppermint - Walker', 66.89);
insert into PRODUCT (title, price) values ('Corn Kernels - Frozen', 56.3);
insert into PRODUCT (title, price) values ('Lettuce - Iceberg', 82.15);
insert into PRODUCT (title, price) values ('Wine - Ruffino Chianti', 26.84);
insert into PRODUCT (title, price) values ('Ham - Procutinni', 72.96);
insert into PRODUCT (title, price) values ('Mudslide', 32.82);
insert into PRODUCT (title, price) values ('Salmon - Canned', 87.63);
insert into PRODUCT (title, price) values ('Vinegar - Sherry', 41.37);
insert into PRODUCT (title, price) values ('Tomato Puree', 63.7);
insert into PRODUCT (title, price) values ('Beer - Mill St Organic', 72.88);
insert into PRODUCT (title, price) values ('Ecolab - Orange Frc, Cleaner', 96.74);
insert into PRODUCT (title, price) values ('Apple - Delicious, Golden', 33.83);
insert into PRODUCT (title, price) values ('Cocoa Powder - Natural', 83.7);
insert into PRODUCT (title, price) values ('Bread - Bistro White', 87.05);
insert into PRODUCT (title, price) values ('Juice - Apple, 341 Ml', 92.54);
insert into PRODUCT (title, price) values ('Pears - Bartlett', 28.05);
insert into PRODUCT (title, price) values ('Beef - Outside, Round', 57.12);
insert into PRODUCT (title, price) values ('Beer - Sleemans Cream Ale', 71.09);
insert into PRODUCT (title, price) values ('Ezy Change Mophandle', 39.02);
insert into PRODUCT (title, price) values ('Lobster - Tail 6 Oz', 75.72);
insert into PRODUCT (title, price) values ('Bouq All Italian - Primerba', 43.8);
insert into PRODUCT (title, price) values ('Liqueur Banana, Ramazzotti', 72.68);
insert into PRODUCT (title, price) values ('Spice - Montreal Steak Spice', 55.17);
insert into PRODUCT (title, price) values ('Nut - Walnut, Chopped', 28.37);
insert into PRODUCT (title, price) values ('Wine - Domaine Boyar Royal', 24.04);
insert into PRODUCT (title, price) values ('Rum - Mount Gay Eclipes', 56.9);
insert into PRODUCT (title, price) values ('Salt - Rock, Course', 62.9);
insert into PRODUCT (title, price) values ('Lotus Leaves', 39.93);
insert into PRODUCT (title, price) values ('Paper Towel Touchless', 31.21);
insert into PRODUCT (title, price) values ('Aspic - Clear', 34.7);
insert into PRODUCT (title, price) values ('Vaccum Bag - 14x20', 47.09);
insert into PRODUCT (title, price) values ('Wine - Magnotta - Cab Sauv', 70.86);
insert into PRODUCT (title, price) values ('Pur Value', 49.54);
insert into PRODUCT (title, price) values ('Tia Maria', 74.94);
insert into PRODUCT (title, price) values ('Lettuce - Boston Bib', 60.93);
insert into PRODUCT (title, price) values ('Ham Black Forest', 58.41);
insert into PRODUCT (title, price) values ('Soup - Boston Clam Chowder', 65.47);
insert into PRODUCT (title, price) values ('Oil - Canola', 90.15);
insert into PRODUCT (title, price) values ('Horseradish Root', 79.0);
insert into PRODUCT (title, price) values ('Ecolab - Power Fusion', 72.47);
insert into PRODUCT (title, price) values ('Beer - Upper Canada Light', 49.38);
insert into PRODUCT (title, price) values ('Cheese - Perron Cheddar', 48.95);
insert into PRODUCT (title, price) values ('Syrup - Monin - Passion Fruit', 19.74);
insert into PRODUCT (title, price) values ('Bamboo Shoots - Sliced', 23.93);
insert into PRODUCT (title, price) values ('Lychee', 32.58);
insert into PRODUCT (title, price) values ('Lettuce - Curly Endive', 25.04);
insert into PRODUCT (title, price) values ('French Pastries', 93.22);
insert into PRODUCT (title, price) values ('Pasta - Orecchiette', 70.67);
insert into PRODUCT (title, price) values ('Steam Pan - Half Size Deep', 84.42);
insert into PRODUCT (title, price) values ('Pate - Cognac', 20.41);
insert into PRODUCT (title, price) values ('Shrimp - 150 - 250', 98.07);
insert into PRODUCT (title, price) values ('Pork - Chop, Frenched', 86.57);
insert into PRODUCT (title, price) values ('Cups 10oz Trans', 11.04);
insert into PRODUCT (title, price) values ('Vegetable - Base', 27.28);
insert into PRODUCT (title, price) values ('Chips Potato Swt Chilli Sour', 46.84);
insert into PRODUCT (title, price) values ('Pasta - Fettuccine, Dry', 62.5);
insert into PRODUCT (title, price) values ('Mushrooms - Black, Dried', 51.24);
insert into PRODUCT (title, price) values ('Cleaner - Bleach', 33.06);
insert into PRODUCT (title, price) values ('Beans - Long, Chinese', 33.49);
insert into PRODUCT (title, price) values ('Lemon Pepper', 32.6);
insert into PRODUCT (title, price) values ('Anchovy Fillets', 91.12);
insert into PRODUCT (title, price) values ('Rabbit - Frozen', 53.45);
insert into PRODUCT (title, price) values ('Halibut - Fletches', 61.99);
insert into PRODUCT (title, price) values ('Shiratamako - Rice Flour', 65.28);
insert into PRODUCT (title, price) values ('Carrots - Mini Red Organic', 91.35);
insert into PRODUCT (title, price) values ('Ecolab - Balanced Fusion', 73.56);
insert into PRODUCT (title, price) values ('Cheese - Bocconcini', 38.74);
insert into PRODUCT (title, price) values ('Beer - Pilsner Urquell', 24.56);
insert into PRODUCT (title, price) values ('Oneshot Automatic Soap System', 45.98);
insert into PRODUCT (title, price) values ('Truffle Shells - Semi - Sweet', 20.62);
insert into PRODUCT (title, price) values ('Milk - Chocolate 500ml', 24.13);
insert into PRODUCT (title, price) values ('Bread - Pumpernickel', 42.97);
insert into PRODUCT (title, price) values ('Muffin Mix - Raisin Bran', 49.82);
insert into PRODUCT (title, price) values ('Beef - Tenderloin', 33.07);
insert into PRODUCT (title, price) values ('Irish Cream - Baileys', 57.59);
insert into PRODUCT (title, price) values ('Chickensplit Half', 29.56);
insert into PRODUCT (title, price) values ('Flour Dark Rye', 46.26);
insert into PRODUCT (title, price) values ('Crab - Soft Shell', 44.23);
insert into PRODUCT (title, price) values ('Mushroom - Oyster, Fresh', 80.53);
insert into PRODUCT (title, price) values ('Beef - Bones, Marrow', 78.51);
insert into PRODUCT (title, price) values ('Bagel - Ched Chs Presliced', 34.4);
insert into PRODUCT (title, price) values ('Bread - Flat Bread', 20.9);
insert into PRODUCT (title, price) values ('Vinegar - White Wine', 63.6);
insert into PRODUCT (title, price) values ('Soup - Base Broth Chix', 75.55);
insert into PRODUCT (title, price) values ('Wine - Taylors Reserve', 95.38);
insert into PRODUCT (title, price) values ('Honey - Lavender', 81.33);
insert into PRODUCT (title, price) values ('The Pop Shoppe - Lime Rickey', 43.11);
insert into PRODUCT (title, price) values ('Mushroom - Trumpet, Dry', 90.98);
insert into PRODUCT (title, price) values ('Coffee - Espresso', 14.58);
insert into PRODUCT (title, price) values ('Sprouts - Corn', 20.15);
insert into PRODUCT (title, price) values ('Apples - Sliced / Wedge', 10.64);
insert into PRODUCT (title, price) values ('Ham - Proscuitto', 15.11);
insert into PRODUCT (title, price) values ('Island Oasis - Magarita Mix', 63.71);
insert into PRODUCT (title, price) values ('Wine - Chateau Aqueria Tavel', 68.44);
insert into PRODUCT (title, price) values ('Milk - Skim', 93.68);
insert into PRODUCT (title, price) values ('Wine - Saint - Bris 2002, Sauv', 70.4);
insert into PRODUCT (title, price) values ('Daikon Radish', 85.33);
insert into PRODUCT (title, price) values ('Danishes - Mini Raspberry', 62.13);
insert into PRODUCT (title, price) values ('Pork - Bacon, Double Smoked', 15.29);
insert into PRODUCT (title, price) values ('Towel - Roll White', 52.72);
insert into PRODUCT (title, price) values ('Broom - Push', 81.05);
insert into PRODUCT (title, price) values ('Wine - Chianti Classica Docg', 80.14);
insert into PRODUCT (title, price) values ('Pork - Loin, Center Cut', 69.35);
insert into PRODUCT (title, price) values ('Pepper - Green', 84.96);
insert into PRODUCT (title, price) values ('Mace Ground', 46.38);
insert into PRODUCT (title, price) values ('Remy Red', 41.83);
insert into PRODUCT (title, price) values ('Puff Pastry - Sheets', 12.28);
insert into PRODUCT (title, price) values ('Flour - Cake', 26.37);
insert into PRODUCT (title, price) values ('Calaloo', 87.13);
insert into PRODUCT (title, price) values ('Sauce - Cranberry', 31.15);
insert into PRODUCT (title, price) values ('Beef - Top Butt', 12.83);
insert into PRODUCT (title, price) values ('Olives - Stuffed', 75.36);
insert into PRODUCT (title, price) values ('Chicken - Leg / Back Attach', 70.75);
insert into PRODUCT (title, price) values ('Lid Tray - 12in Dome', 21.41);
insert into PRODUCT (title, price) values ('Soda Water - Club Soda, 355 Ml', 98.19);
insert into PRODUCT (title, price) values ('Pepper - Gypsy Pepper', 81.44);
insert into PRODUCT (title, price) values ('Coffee - Cafe Moreno', 93.71);
insert into PRODUCT (title, price) values ('Cheese - Parmesan Cubes', 99.17);
insert into PRODUCT (title, price) values ('Tuna - Bluefin', 67.99);
insert into PRODUCT (title, price) values ('Energy Drink - Franks Original', 47.02);
insert into PRODUCT (title, price) values ('Shichimi Togarashi Peppeers', 77.57);
insert into PRODUCT (title, price) values ('Yoghurt Tubes', 72.14);
insert into PRODUCT (title, price) values ('Beef - Bresaola', 55.19);
insert into PRODUCT (title, price) values ('Chips Potato All Dressed - 43g', 26.82);
insert into PRODUCT (title, price) values ('Wine - Beringer Founders Estate', 44.33);
insert into PRODUCT (title, price) values ('Carbonated Water - Strawberry', 30.73);
insert into PRODUCT (title, price) values ('Sauce - Oyster', 18.21);
insert into PRODUCT (title, price) values ('Carbonated Water - Cherry', 70.97);
insert into PRODUCT (title, price) values ('Butter - Pod', 25.2);
insert into PRODUCT (title, price) values ('Oregano - Fresh', 94.31);
insert into PRODUCT (title, price) values ('Spice - Greek 1 Step', 57.18);
insert into PRODUCT (title, price) values ('Wine - Alicanca Vinho Verde', 48.83);
insert into PRODUCT (title, price) values ('Table Cloth 53x53 White', 64.89);
insert into PRODUCT (title, price) values ('Napkin White', 15.13);
insert into PRODUCT (title, price) values ('Puree - Kiwi', 24.26);
insert into PRODUCT (title, price) values ('Wine - Barbera Alba Doc 2001', 81.14);
insert into PRODUCT (title, price) values ('Lamb - Shanks', 91.58);
insert into PRODUCT (title, price) values ('Wine - Red, Lurton Merlot De', 92.47);
insert into PRODUCT (title, price) values ('Pastrami', 42.72);
insert into PRODUCT (title, price) values ('Wheat - Soft Kernal Of Wheat', 53.33);
insert into PRODUCT (title, price) values ('Muffin Mix - Chocolate Chip', 80.91);
insert into PRODUCT (title, price) values ('Cheese - Comtomme', 43.89);
insert into PRODUCT (title, price) values ('Mushroom - Portebello', 77.98);
insert into PRODUCT (title, price) values ('Wine - Marlbourough Sauv Blanc', 87.92);
insert into PRODUCT (title, price) values ('Pie Shell - 5', 27.77);
insert into PRODUCT (title, price) values ('Beans - French', 27.87);
insert into PRODUCT (title, price) values ('Chips - Potato Jalapeno', 99.94);
insert into PRODUCT (title, price) values ('Compound - Passion Fruit', 51.94);
insert into PRODUCT (title, price) values ('Bread Base - Toscano', 64.23);
insert into PRODUCT (title, price) values ('Salt And Pepper Mix - Black', 89.72);
insert into PRODUCT (title, price) values ('Jolt Cola', 44.71);
insert into PRODUCT (title, price) values ('Eggwhite Frozen', 62.68);
insert into PRODUCT (title, price) values ('Crab - Imitation Flakes', 86.75);
insert into PRODUCT (title, price) values ('Cup - 3.5oz, Foam', 88.68);
insert into PRODUCT (title, price) values ('Tea - Grapefruit Green Tea', 48.75);
insert into PRODUCT (title, price) values ('Wine - Cave Springs Dry Riesling', 43.22);
insert into PRODUCT (title, price) values ('Sweet Pea Sprouts', 28.9);
insert into PRODUCT (title, price) values ('Anchovy Fillets', 15.43);
insert into PRODUCT (title, price) values ('Potatoes - Yukon Gold, 80 Ct', 69.9);
insert into PRODUCT (title, price) values ('Five Alive Citrus', 99.43);
insert into PRODUCT (title, price) values ('Roe - White Fish', 56.35);
insert into PRODUCT (title, price) values ('Chocolate - Pistoles, White', 51.12);
insert into PRODUCT (title, price) values ('Wine - Taylors Reserve', 63.9);
insert into PRODUCT (title, price) values ('Wine - Wyndham Estate Bin 777', 23.24);
insert into PRODUCT (title, price) values ('Yogurt - Banana, 175 Gr', 21.29);
insert into PRODUCT (title, price) values ('Initation Crab Meat', 91.68);
insert into PRODUCT (title, price) values ('Phyllo Dough', 29.63);
insert into PRODUCT (title, price) values ('Carbonated Water - Lemon Lime', 70.95);
insert into PRODUCT (title, price) values ('Pork Loin Cutlets', 53.36);
insert into PRODUCT (title, price) values ('Wine - Fume Blanc Fetzer', 98.6);
insert into PRODUCT (title, price) values ('Soup - French Can Pea', 13.54);
insert into PRODUCT (title, price) values ('Wine - Magnotta - Cab Franc', 87.25);
insert into PRODUCT (title, price) values ('Pasta - Fusili Tri - Coloured', 83.2);
insert into PRODUCT (title, price) values ('Tart Shells - Savory, 2', 21.86);
insert into PRODUCT (title, price) values ('Fondant - Icing', 81.79);
insert into PRODUCT (title, price) values ('Pastry - Baked Cinnamon Stick', 79.73);
insert into PRODUCT (title, price) values ('Breadfruit', 51.38);
insert into PRODUCT (title, price) values ('Wine - Vidal Icewine Magnotta', 86.34);
insert into PRODUCT (title, price) values ('Chicken - White Meat With Tender', 40.36);
insert into PRODUCT (title, price) values ('Macaroons - Two Bite Choc', 72.99);
insert into PRODUCT (title, price) values ('Corn Meal', 80.91);
insert into PRODUCT (title, price) values ('Kirsch - Schloss', 11.69);
insert into PRODUCT (title, price) values ('Passion Fruit', 24.56);
insert into PRODUCT (title, price) values ('Cheese - Cream Cheese', 25.58);
insert into PRODUCT (title, price) values ('Pepper - Orange', 78.56);
insert into PRODUCT (title, price) values ('Sugar Thermometer', 63.55);
insert into PRODUCT (title, price) values ('Dried Peach', 87.38);
insert into PRODUCT (title, price) values ('Pastry - Apple Muffins - Mini', 85.57);
insert into PRODUCT (title, price) values ('Energy Drink Red Bull', 78.8);
insert into PRODUCT (title, price) values ('Irish Cream - Butterscotch', 17.96);
insert into PRODUCT (title, price) values ('Icecream - Dstk Super Cone', 91.68);
insert into PRODUCT (title, price) values ('Pasta - Lasagne, Fresh', 11.34);
insert into PRODUCT (title, price) values ('Port - 74 Brights', 19.51);
insert into PRODUCT (title, price) values ('Container - Hngd Cll Blk 7x7x3', 80.03);
insert into PRODUCT (title, price) values ('Flour - Masa De Harina Mexican', 40.06);
insert into PRODUCT (title, price) values ('Ecolab - Hand Soap Form Antibac', 79.15);
insert into PRODUCT (title, price) values ('Cheese - Shred Cheddar / Mozza', 17.52);
insert into PRODUCT (title, price) values ('Tuna - Yellowfin', 12.75);
insert into PRODUCT (title, price) values ('Bread Crumbs - Panko', 56.91);
insert into PRODUCT (title, price) values ('Roe - Flying Fish', 91.4);
insert into PRODUCT (title, price) values ('Compound - Passion Fruit', 14.83);
insert into PRODUCT (title, price) values ('Tomatoes Tear Drop', 69.69);
insert into PRODUCT (title, price) values ('Tomatoes - Plum, Canned', 85.31);
insert into PRODUCT (title, price) values ('Wine - Piper Heidsieck Brut', 98.23);
insert into PRODUCT (title, price) values ('Mushroom - Lg - Cello', 42.15);
insert into PRODUCT (title, price) values ('Chicken - White Meat, No Tender', 50.25);
insert into PRODUCT (title, price) values ('Apricots - Dried', 90.17);
insert into PRODUCT (title, price) values ('Sponge Cake Mix - Vanilla', 66.66);
insert into PRODUCT (title, price) values ('Lamb Tenderloin Nz Fr', 59.54);
insert into PRODUCT (title, price) values ('Plate - Foam, Bread And Butter', 38.26);
insert into PRODUCT (title, price) values ('Pastry - Trippleberry Muffin - Mini', 57.34);
insert into PRODUCT (title, price) values ('Cranberries - Frozen', 41.05);
insert into PRODUCT (title, price) values ('Wine - Chardonnay Mondavi', 64.53);
insert into PRODUCT (title, price) values ('Nut - Cashews, Whole, Raw', 64.1);
insert into PRODUCT (title, price) values ('Sole - Iqf', 76.31);
insert into PRODUCT (title, price) values ('Lentils - Green Le Puy', 21.87);
insert into PRODUCT (title, price) values ('Artichokes - Jerusalem', 94.76);
insert into PRODUCT (title, price) values ('Spinach - Packaged', 88.66);
insert into PRODUCT (title, price) values ('Hersey Shakes', 19.94);
insert into PRODUCT (title, price) values ('Veal - Chops, Split, Frenched', 50.19);
insert into PRODUCT (title, price) values ('Milk - Skim', 26.72);
insert into PRODUCT (title, price) values ('Beef - Baby, Liver', 24.85);
insert into PRODUCT (title, price) values ('Wine - Wyndham Estate Bin 777', 37.9);
insert into PRODUCT (title, price) values ('Cake - Bande Of Fruit', 29.51);
insert into PRODUCT (title, price) values ('Beer - Blue Light', 92.48);
insert into PRODUCT (title, price) values ('Appetizer - Shrimp Puff', 17.63);
insert into PRODUCT (title, price) values ('Ice Cream - Vanilla', 45.78);
insert into PRODUCT (title, price) values ('Bread - Roll, Whole Wheat', 79.1);
insert into PRODUCT (title, price) values ('Wine - Lou Black Shiraz', 96.07);
insert into PRODUCT (title, price) values ('Glycerine', 49.97);
insert into PRODUCT (title, price) values ('Wine - Sawmill Creek Autumn', 94.3);
insert into PRODUCT (title, price) values ('Nut - Macadamia', 36.59);
insert into PRODUCT (title, price) values ('Wine - Carmenere Casillero Del', 11.9);
insert into PRODUCT (title, price) values ('Cod - Fillets', 27.38);
insert into PRODUCT (title, price) values ('Energy Drink', 33.82);
insert into PRODUCT (title, price) values ('Sauce - Alfredo', 63.3);
insert into PRODUCT (title, price) values ('Chicken - Bones', 89.3);
insert into PRODUCT (title, price) values ('Shrimp - Black Tiger 8 - 12', 68.8);
insert into PRODUCT (title, price) values ('Nantucket Apple Juice', 75.35);
insert into PRODUCT (title, price) values ('Blueberries', 24.61);
insert into PRODUCT (title, price) values ('Taro Leaves', 56.62);
insert into PRODUCT (title, price) values ('Vol Au Vents', 29.08);
insert into PRODUCT (title, price) values ('Towel Dispenser', 37.43);
insert into PRODUCT (title, price) values ('Carroway Seed', 73.89);
insert into PRODUCT (title, price) values ('Cake - Cake Sheet Macaroon', 60.18);
insert into PRODUCT (title, price) values ('Taro Leaves', 79.95);
insert into PRODUCT (title, price) values ('Whmis - Spray Bottle Trigger', 25.82);
insert into PRODUCT (title, price) values ('Tomatoes - Vine Ripe, Yellow', 44.81);
insert into PRODUCT (title, price) values ('Sobe - Lizard Fuel', 49.5);
insert into PRODUCT (title, price) values ('Chicken - Tenderloin', 95.24);
insert into PRODUCT (title, price) values ('Wine - Pinot Noir Stoneleigh', 94.09);
insert into PRODUCT (title, price) values ('Danishes - Mini Raspberry', 86.89);
insert into PRODUCT (title, price) values ('Cake - Bande Of Fruit', 29.23);
insert into PRODUCT (title, price) values ('Pork - Loin, Boneless', 55.06);
insert into PRODUCT (title, price) values ('Venison - Liver', 26.92);
insert into PRODUCT (title, price) values ('Pork - Smoked Kassler', 76.2);
insert into PRODUCT (title, price) values ('Cookies - Englishbay Chochip', 92.44);
insert into PRODUCT (title, price) values ('Carbonated Water - Blackcherry', 47.96);
insert into PRODUCT (title, price) values ('Fennel', 51.06);
insert into PRODUCT (title, price) values ('Tuna - Bluefin', 38.22);
insert into PRODUCT (title, price) values ('Longos - Chicken Curried', 43.22);
insert into PRODUCT (title, price) values ('Sausage - Liver', 43.71);
insert into PRODUCT (title, price) values ('Pears - Anjou', 30.07);
insert into PRODUCT (title, price) values ('Juice - Clam, 46 Oz', 73.77);
insert into PRODUCT (title, price) values ('Cream - 35%', 56.01);
insert into PRODUCT (title, price) values ('Beef - Bones, Cut - Up', 56.39);
insert into PRODUCT (title, price) values ('Mace Ground', 88.62);
insert into PRODUCT (title, price) values ('Smoked Paprika', 42.26);
insert into PRODUCT (title, price) values ('Wine - Pinot Noir Pond Haddock', 42.58);
insert into PRODUCT (title, price) values ('Pike - Frozen Fillet', 39.31);
insert into PRODUCT (title, price) values ('Nut - Hazelnut, Ground, Natural', 94.86);
insert into PRODUCT (title, price) values ('Sambuca - Opal Nera', 47.0);
insert into PRODUCT (title, price) values ('Yoghurt Tubes', 22.76);
insert into PRODUCT (title, price) values ('Bread - Pullman, Sliced', 86.29);
insert into PRODUCT (title, price) values ('Peas - Pigeon, Dry', 98.66);
insert into PRODUCT (title, price) values ('Veal - Heart', 74.1);
insert into PRODUCT (title, price) values ('Dill Weed - Fresh', 77.2);
insert into PRODUCT (title, price) values ('Sauce - Rosee', 12.51);
insert into PRODUCT (title, price) values ('Oats Large Flake', 80.15);
insert into PRODUCT (title, price) values ('Bag - Regular Kraft 20 Lb', 56.67);
insert into PRODUCT (title, price) values ('Lamb - Shoulder, Boneless', 98.23);
insert into PRODUCT (title, price) values ('Trout - Rainbow, Frozen', 62.84);
insert into PRODUCT (title, price) values ('Turkey Leg With Drum And Thigh', 28.23);
insert into PRODUCT (title, price) values ('Turkey - Whole, Fresh', 54.34);
insert into PRODUCT (title, price) values ('Cheese - Cream Cheese', 15.39);
insert into PRODUCT (title, price) values ('Beets', 38.86);
insert into PRODUCT (title, price) values ('Nectarines', 58.45);
insert into PRODUCT (title, price) values ('Cheese - Gouda Smoked', 60.36);
insert into PRODUCT (title, price) values ('Butter Sweet', 70.86);
insert into PRODUCT (title, price) values ('Appetizer - Seafood Assortment', 15.11);
insert into PRODUCT (title, price) values ('Pork - Suckling Pig', 76.3);
insert into PRODUCT (title, price) values ('Kiwi Gold Zespri', 39.6);
insert into PRODUCT (title, price) values ('Wine - Rhine Riesling Wolf Blass', 22.34);
insert into PRODUCT (title, price) values ('Tart - Butter Plain Squares', 59.55);
insert into PRODUCT (title, price) values ('Wine - White, Ej', 77.23);
insert into PRODUCT (title, price) values ('Shortbread - Cookie Crumbs', 63.9);
insert into PRODUCT (title, price) values ('Lobster - Base', 60.21);
insert into PRODUCT (title, price) values ('Sauce - Roasted Red Pepper', 15.21);
insert into PRODUCT (title, price) values ('Tilapia - Fillets', 37.05);
insert into PRODUCT (title, price) values ('Lobster - Base', 51.8);
insert into PRODUCT (title, price) values ('Radish', 69.51);
insert into PRODUCT (title, price) values ('Bread - Rolls, Rye', 35.04);
insert into PRODUCT (title, price) values ('Soup - Canadian Pea, Dry Mix', 57.22);
insert into PRODUCT (title, price) values ('Sun - Dried Tomatoes', 47.19);
insert into PRODUCT (title, price) values ('Appetizer - Spring Roll, Veg', 70.73);
insert into PRODUCT (title, price) values ('Raspberries - Frozen', 57.1);
insert into PRODUCT (title, price) values ('Sauce - Gravy, Au Jus, Mix', 64.11);
insert into PRODUCT (title, price) values ('Langers - Cranberry Cocktail', 53.53);
insert into PRODUCT (title, price) values ('Mahi Mahi', 23.78);
insert into PRODUCT (title, price) values ('Rabbit - Whole', 80.38);
insert into PRODUCT (title, price) values ('Wine - Kwv Chenin Blanc South', 15.42);
insert into PRODUCT (title, price) values ('Bagel - Whole White Sesame', 71.69);
insert into PRODUCT (title, price) values ('Glaze - Apricot', 97.08);
insert into PRODUCT (title, price) values ('Nut - Walnut, Chopped', 31.81);
insert into PRODUCT (title, price) values ('Chocolate - White', 65.97);
insert into PRODUCT (title, price) values ('Oil - Sesame', 67.71);
insert into PRODUCT (title, price) values ('Beef - Inside Round', 61.02);
insert into PRODUCT (title, price) values ('Burger Veggie', 37.96);
insert into PRODUCT (title, price) values ('Dip - Tapenade', 65.19);
insert into PRODUCT (title, price) values ('Ecolab - Ster Bac', 95.92);
insert into PRODUCT (title, price) values ('Pomello', 74.97);
insert into PRODUCT (title, price) values ('Container Clear 8 Oz', 34.24);
insert into PRODUCT (title, price) values ('Trueblue - Blueberry 12x473ml', 91.4);
insert into PRODUCT (title, price) values ('Beef - Ground Medium', 86.17);
insert into PRODUCT (title, price) values ('Ham - Cooked Italian', 66.76);
insert into PRODUCT (title, price) values ('Beef - Rib Roast, Capless', 66.81);
insert into PRODUCT (title, price) values ('Table Cloth - 53x69 Colour', 46.1);
insert into PRODUCT (title, price) values ('Chocolate - Pistoles, White', 78.0);
insert into PRODUCT (title, price) values ('Sobe - Orange Carrot', 38.3);
insert into PRODUCT (title, price) values ('Dip - Tapenade', 60.03);
insert into PRODUCT (title, price) values ('Tea - Herbal - 6 Asst', 72.89);
insert into PRODUCT (title, price) values ('Cake - Box Window 10x10x2.5', 14.77);
insert into PRODUCT (title, price) values ('Beets - Mini Golden', 57.6);
insert into PRODUCT (title, price) values ('Shiro Miso', 23.59);
insert into PRODUCT (title, price) values ('Raisin - Dark', 66.74);
insert into PRODUCT (title, price) values ('Creme De Cacao White', 36.41);
insert into PRODUCT (title, price) values ('Pie Shell - 9', 69.46);
insert into PRODUCT (title, price) values ('Bagel - Everything', 20.65);
insert into PRODUCT (title, price) values ('Banana - Leaves', 95.31);
insert into PRODUCT (title, price) values ('Kirsch - Schloss', 28.79);
insert into PRODUCT (title, price) values ('Versatainer Nc - 888', 84.95);
insert into PRODUCT (title, price) values ('Mousse - Mango', 47.53);
insert into PRODUCT (title, price) values ('Bread - French Baquette', 22.18);
insert into PRODUCT (title, price) values ('Beef - Rib Roast, Capless', 53.44);
insert into PRODUCT (title, price) values ('Snapple - Mango Maddness', 11.49);
insert into PRODUCT (title, price) values ('Grouper - Fresh', 37.86);
insert into PRODUCT (title, price) values ('Wine - White, Chardonnay', 67.22);
insert into PRODUCT (title, price) values ('Puff Pastry - Slab', 38.13);
insert into PRODUCT (title, price) values ('Sauce - Vodka Blush', 39.78);
insert into PRODUCT (title, price) values ('Sage Derby', 10.91);
insert into PRODUCT (title, price) values ('Bay Leaf Fresh', 22.34);
insert into PRODUCT (title, price) values ('Mcgillicuddy Vanilla Schnap', 71.99);
insert into PRODUCT (title, price) values ('Soup - Campbells, Creamy', 90.71);
insert into PRODUCT (title, price) values ('Soup - Campbells Beef Strogonoff', 42.28);
insert into PRODUCT (title, price) values ('Oven Mitts 17 Inch', 76.61);
insert into PRODUCT (title, price) values ('Wasabi Paste', 95.47);
insert into PRODUCT (title, price) values ('Wine - Prosecco Valdobienne', 72.16);
insert into PRODUCT (title, price) values ('Pepper - Green', 21.01);
insert into PRODUCT (title, price) values ('Wine - Remy Pannier Rose', 25.41);
insert into PRODUCT (title, price) values ('Pork - Side Ribs', 32.73);
insert into PRODUCT (title, price) values ('Wine - White, Lindemans Bin 95', 37.74);
insert into PRODUCT (title, price) values ('Langers - Ruby Red Grapfruit', 83.68);
insert into PRODUCT (title, price) values ('Pepper - Black, Ground', 19.94);
insert into PRODUCT (title, price) values ('Star Anise, Whole', 32.4);
insert into PRODUCT (title, price) values ('Asparagus - Green, Fresh', 79.06);
insert into PRODUCT (title, price) values ('Red Pepper Paste', 26.6);
insert into PRODUCT (title, price) values ('Amaretto', 30.15);
insert into PRODUCT (title, price) values ('Chocolate - Chips Compound', 60.35);
insert into PRODUCT (title, price) values ('Halibut - Fletches', 14.76);
insert into PRODUCT (title, price) values ('Syrup - Monin - Blue Curacao', 88.19);
insert into PRODUCT (title, price) values ('Wine - White, Concha Y Toro', 71.57);
insert into PRODUCT (title, price) values ('Soup V8 Roasted Red Pepper', 91.59);
insert into PRODUCT (title, price) values ('Apple - Granny Smith', 57.44);
insert into PRODUCT (title, price) values ('Sauce - Hp', 71.22);
insert into PRODUCT (title, price) values ('Pastry - Chocolate Marble Tea', 90.06);
insert into PRODUCT (title, price) values ('Table Cloth 62x114 Colour', 26.84);
insert into PRODUCT (title, price) values ('Dried Peach', 97.56);
insert into PRODUCT (title, price) values ('Banana - Green', 24.11);
insert into PRODUCT (title, price) values ('Bouq All Italian - Primerba', 13.56);
insert into PRODUCT (title, price) values ('Table Cloth 62x120 Colour', 56.41);
insert into PRODUCT (title, price) values ('Mousse - Banana Chocolate', 25.41);
insert into PRODUCT (title, price) values ('Bread - Raisin Walnut Pull', 36.07);
insert into PRODUCT (title, price) values ('Wine - Saint Emilion Calvet', 56.58);
insert into PRODUCT (title, price) values ('Compound - Mocha', 16.4);
insert into PRODUCT (title, price) values ('Flour - Bran, Red', 56.56);
insert into PRODUCT (title, price) values ('Sugar - Sweet N Low, Individual', 32.46);
insert into PRODUCT (title, price) values ('Sambuca - Ramazzotti', 28.63);
insert into PRODUCT (title, price) values ('Paper - Brown Paper Mini Cups', 49.07);
insert into PRODUCT (title, price) values ('Soupfoamcont12oz 112con', 32.54);
insert into PRODUCT (title, price) values ('Chicken - White Meat, No Tender', 15.07);
insert into PRODUCT (title, price) values ('Baking Soda', 75.72);
insert into PRODUCT (title, price) values ('Gatorade - Lemon Lime', 99.84);
insert into PRODUCT (title, price) values ('Crab - Blue, Frozen', 40.12);
insert into PRODUCT (title, price) values ('Food Colouring - Orange', 40.07);
insert into PRODUCT (title, price) values ('Raspberries - Frozen', 74.36);
insert into PRODUCT (title, price) values ('Cleaner - Lime Away', 21.01);
insert into PRODUCT (title, price) values ('Wine - Black Tower Qr', 43.36);
insert into PRODUCT (title, price) values ('Sprouts - China Rose', 40.95);
insert into PRODUCT (title, price) values ('Bread Foccacia Whole', 59.58);
insert into PRODUCT (title, price) values ('Apple - Royal Gala', 38.72);
insert into PRODUCT (title, price) values ('Skirt - 29 Foot', 99.38);
insert into PRODUCT (title, price) values ('White Fish - Filets', 56.48);
insert into PRODUCT (title, price) values ('Tilapia - Fillets', 15.35);
insert into PRODUCT (title, price) values ('Nut - Chestnuts, Whole', 51.95);
insert into PRODUCT (title, price) values ('Peach - Fresh', 11.08);
insert into PRODUCT (title, price) values ('Coke - Classic, 355 Ml', 97.47);
insert into PRODUCT (title, price) values ('Versatainer Nc - 888', 51.95);
insert into PRODUCT (title, price) values ('Appetizer - Sausage Rolls', 94.39);
insert into PRODUCT (title, price) values ('Soup V8 Roasted Red Pepper', 48.34);
insert into PRODUCT (title, price) values ('Soap - Mr.clean Floor Soap', 18.48);
insert into PRODUCT (title, price) values ('Juice - Cranberry, 341 Ml', 48.24);
insert into PRODUCT (title, price) values ('Ham - Virginia', 99.74);
insert into PRODUCT (title, price) values ('Grapefruit - White', 99.26);
insert into PRODUCT (title, price) values ('Wine - Pinot Noir Mondavi Coastal', 18.93);
insert into PRODUCT (title, price) values ('Croissants Thaw And Serve', 84.56);
insert into PRODUCT (title, price) values ('Wine - Marlbourough Sauv Blanc', 37.03);
insert into PRODUCT (title, price) values ('Tomatoes - Hot House', 13.84);
insert into PRODUCT (title, price) values ('Puree - Blackcurrant', 27.03);
insert into PRODUCT (title, price) values ('Tomatoes - Yellow Hot House', 50.98);
insert into PRODUCT (title, price) values ('Doilies - 7, Paper', 52.62);
insert into PRODUCT (title, price) values ('Venison - Denver Leg Boneless', 44.22);
insert into PRODUCT (title, price) values ('Tart - Butter Plain Squares', 16.64);
insert into PRODUCT (title, price) values ('Wine - Black Tower Qr', 77.62);
insert into PRODUCT (title, price) values ('Scallops - 20/30', 83.19);
insert into PRODUCT (title, price) values ('Bread - Rolls, Corn', 50.51);
insert into PRODUCT (title, price) values ('Pork - Tenderloin, Frozen', 78.33);
insert into PRODUCT (title, price) values ('Wine - White, Antinore Orvieto', 16.65);
insert into PRODUCT (title, price) values ('Beans - Wax', 17.73);
insert into PRODUCT (title, price) values ('Lettuce - Spring Mix', 38.78);
insert into PRODUCT (title, price) values ('Nantucket - Pomegranate Pear', 95.51);
insert into PRODUCT (title, price) values ('Lotus Rootlets - Canned', 53.41);
insert into PRODUCT (title, price) values ('Carrots - Mini Red Organic', 73.58);
insert into PRODUCT (title, price) values ('Pepper - Red, Finger Hot', 65.0);
insert into PRODUCT (title, price) values ('Burger Veggie', 33.49);
insert into PRODUCT (title, price) values ('Aspic - Light', 26.95);
insert into PRODUCT (title, price) values ('Wine - Red, Cooking', 38.47);
insert into PRODUCT (title, price) values ('Extract - Vanilla,artificial', 29.67);
insert into PRODUCT (title, price) values ('Lid - Translucent, 3.5 And 6 Oz', 50.57);
insert into PRODUCT (title, price) values ('Wine - Zinfandel California 2002', 40.77);
insert into PRODUCT (title, price) values ('Scallop - St. Jaques', 39.47);
insert into PRODUCT (title, price) values ('Soup - Campbells, Spinach Crm', 76.58);
insert into PRODUCT (title, price) values ('Langers - Mango Nectar', 74.69);
insert into PRODUCT (title, price) values ('Pasta - Lasagna, Dry', 86.59);
insert into PRODUCT (title, price) values ('Marjoram - Dried, Rubbed', 45.5);
insert into PRODUCT (title, price) values ('Grouper - Fresh', 36.55);
insert into PRODUCT (title, price) values ('Wine - Zonnebloem Pinotage', 18.93);
insert into PRODUCT (title, price) values ('Bread - White, Sliced', 41.48);
insert into PRODUCT (title, price) values ('Lamb - Shoulder', 82.82);
insert into PRODUCT (title, price) values ('Sprouts - China Rose', 93.13);
insert into PRODUCT (title, price) values ('Wine - Crozes Hermitage E.', 93.33);
insert into PRODUCT (title, price) values ('Cheese - Feta', 29.71);
insert into PRODUCT (title, price) values ('Dikon', 16.1);
insert into PRODUCT (title, price) values ('Cornish Hen', 37.66);
insert into PRODUCT (title, price) values ('Ice Cream Bar - Oreo Cone', 70.58);
insert into PRODUCT (title, price) values ('Pepperoni Slices', 86.5);
insert into PRODUCT (title, price) values ('Chinese Foods - Thick Noodles', 19.72);
insert into PRODUCT (title, price) values ('Miso Paste White', 72.43);
insert into PRODUCT (title, price) values ('Food Colouring - Pink', 64.51);
insert into PRODUCT (title, price) values ('Tomatoes - Vine Ripe, Yellow', 75.42);
insert into PRODUCT (title, price) values ('Wine - George Duboeuf Rose', 45.95);
insert into PRODUCT (title, price) values ('Chocolate Liqueur - Godet White', 62.16);
insert into PRODUCT (title, price) values ('Crab - Back Fin Meat, Canned', 96.13);
insert into PRODUCT (title, price) values ('Tomatoes - Cherry', 44.77);
insert into PRODUCT (title, price) values ('Pepper - Yellow Bell', 73.95);
insert into PRODUCT (title, price) values ('Seabream Whole Farmed', 50.84);
insert into PRODUCT (title, price) values ('Rum - Coconut, Malibu', 69.22);
insert into PRODUCT (title, price) values ('Arctic Char - Fresh, Whole', 38.96);
insert into PRODUCT (title, price) values ('Vinegar - Red Wine', 47.78);
insert into PRODUCT (title, price) values ('Island Oasis - Sweet And Sour Mix', 85.22);
insert into PRODUCT (title, price) values ('Soup - Cream Of Broccoli', 16.55);
insert into PRODUCT (title, price) values ('Mayonnaise - Individual Pkg', 20.25);
insert into PRODUCT (title, price) values ('Shrimp - Prawn', 32.98);
insert into PRODUCT (title, price) values ('French Pastries', 66.93);
insert into PRODUCT (title, price) values ('Pancetta', 13.73);
insert into PRODUCT (title, price) values ('Liqueur Banana, Ramazzotti', 32.45);
insert into PRODUCT (title, price) values ('Cookie - Oatmeal', 45.95);
insert into PRODUCT (title, price) values ('Cocoa Butter', 49.01);
insert into PRODUCT (title, price) values ('Saskatoon Berries - Frozen', 20.0);
insert into PRODUCT (title, price) values ('Lentils - Green Le Puy', 42.91);
insert into PRODUCT (title, price) values ('Soup - Campbells Broccoli', 19.99);
insert into PRODUCT (title, price) values ('Initation Crab Meat', 81.15);
insert into PRODUCT (title, price) values ('Onions - Red', 35.28);
insert into PRODUCT (title, price) values ('Placemat - Scallop, White', 68.49);
insert into PRODUCT (title, price) values ('Potatoes - Pei 10 Oz', 64.14);
insert into PRODUCT (title, price) values ('Bread - Sour Batard', 76.92);
insert into PRODUCT (title, price) values ('Filo Dough', 26.31);
insert into PRODUCT (title, price) values ('Yucca', 86.02);
insert into PRODUCT (title, price) values ('Carbonated Water - White Grape', 90.47);
insert into PRODUCT (title, price) values ('Dc Hikiage Hira Huba', 38.18);
insert into PRODUCT (title, price) values ('White Fish - Filets', 51.05);
insert into PRODUCT (title, price) values ('Teriyaki Sauce', 64.74);
insert into PRODUCT (title, price) values ('Pear - Asian', 86.56);
insert into PRODUCT (title, price) values ('Corn - Mini', 27.8);
insert into PRODUCT (title, price) values ('Table Cloth 91x91 Colour', 23.21);
insert into PRODUCT (title, price) values ('Tuna - Bluefin', 86.84);
insert into PRODUCT (title, price) values ('V8 - Berry Blend', 13.87);
insert into PRODUCT (title, price) values ('Wine - Jaboulet Cotes Du Rhone', 38.94);
insert into PRODUCT (title, price) values ('Vinegar - Red Wine', 60.24);
insert into PRODUCT (title, price) values ('Vanilla Beans', 21.39);
insert into PRODUCT (title, price) values ('Oyster - In Shell', 83.28);
insert into PRODUCT (title, price) values ('Tea - Lemon Scented', 22.45);
insert into PRODUCT (title, price) values ('Ham - Virginia', 41.47);
insert into PRODUCT (title, price) values ('Glaze - Clear', 48.72);
insert into PRODUCT (title, price) values ('Seedlings - Mix, Organic', 34.09);
insert into PRODUCT (title, price) values ('Sprouts - Onion', 34.29);
insert into PRODUCT (title, price) values ('Lettuce - Arugula', 33.8);
insert into PRODUCT (title, price) values ('Kiwi Gold Zespri', 90.07);
insert into PRODUCT (title, price) values ('Rosemary - Fresh', 23.74);
insert into PRODUCT (title, price) values ('Garbage Bags - Black', 51.53);
insert into PRODUCT (title, price) values ('Sea Urchin', 94.9);
insert into PRODUCT (title, price) values ('Vector Energy Bar', 93.62);
insert into PRODUCT (title, price) values ('Lettuce - Green Leaf', 72.5);
insert into PRODUCT (title, price) values ('Pastry - Apple Muffins - Mini', 24.68);
insert into PRODUCT (title, price) values ('Dried Apple', 69.6);
insert into PRODUCT (title, price) values ('Compound - Rum', 72.18);
insert into PRODUCT (title, price) values ('Pepper - Chillies, Crushed', 80.45);
insert into PRODUCT (title, price) values ('Raspberries - Frozen', 61.41);
insert into PRODUCT (title, price) values ('Bread - Bistro Sour', 66.04);
insert into PRODUCT (title, price) values ('Chicken - White Meat With Tender', 62.66);
insert into PRODUCT (title, price) values ('Juice - Apple, 500 Ml', 32.67);
insert into PRODUCT (title, price) values ('Pork - Backfat', 24.03);
insert into PRODUCT (title, price) values ('Wine - Malbec Trapiche Reserve', 74.7);
insert into PRODUCT (title, price) values ('Bacardi Breezer - Tropical', 94.9);
insert into PRODUCT (title, price) values ('Snails - Large Canned', 95.93);
insert into PRODUCT (title, price) values ('Blueberries - Frozen', 92.31);
insert into PRODUCT (title, price) values ('Chicken - Base', 53.75);
insert into PRODUCT (title, price) values ('Ham - Cooked Bayonne Tinned', 16.03);
insert into PRODUCT (title, price) values ('Cranberries - Fresh', 99.78);
insert into PRODUCT (title, price) values ('Olives - Kalamata', 35.07);
insert into PRODUCT (title, price) values ('Lettuce - Baby Salad Greens', 67.25);
insert into PRODUCT (title, price) values ('Wine - Prem Select Charddonany', 83.7);
insert into PRODUCT (title, price) values ('Papayas', 41.46);
insert into PRODUCT (title, price) values ('Flour - Fast / Rapid', 47.91);
insert into PRODUCT (title, price) values ('Bread Base - Italian', 55.44);
insert into PRODUCT (title, price) values ('Trueblue - Blueberry', 74.83);
insert into PRODUCT (title, price) values ('Truffle Shells - Semi - Sweet', 57.53);
insert into PRODUCT (title, price) values ('Table Cloth 62x120 White', 15.49);
insert into PRODUCT (title, price) values ('Wine - Masi Valpolocell', 36.82);
insert into PRODUCT (title, price) values ('Roe - Lump Fish, Red', 22.82);
insert into PRODUCT (title, price) values ('Drambuie', 92.05);
insert into PRODUCT (title, price) values ('Vermouth - White, Cinzano', 94.77);
insert into PRODUCT (title, price) values ('Syrup - Monin - Granny Smith', 48.61);
insert into PRODUCT (title, price) values ('Beef - Ground Lean Fresh', 28.17);
insert into PRODUCT (title, price) values ('Liqueur - Melon', 15.4);
insert into PRODUCT (title, price) values ('Squash - Pattypan, Yellow', 43.26);
insert into PRODUCT (title, price) values ('Icecream - Dstk Strw Chseck', 22.65);
insert into PRODUCT (title, price) values ('Everfresh Products', 36.02);
insert into PRODUCT (title, price) values ('Lotus Root', 72.09);
insert into PRODUCT (title, price) values ('Coffee - Hazelnut Cream', 30.54);
insert into PRODUCT (title, price) values ('Lemon Tarts', 44.09);
insert into PRODUCT (title, price) values ('Coffee Swiss Choc Almond', 80.33);
insert into PRODUCT (title, price) values ('Tray - 16in Rnd Blk', 44.32);
insert into PRODUCT (title, price) values ('Soup - Knorr, Classic Can. Chili', 46.33);
insert into PRODUCT (title, price) values ('Flour - Buckwheat, Dark', 53.72);
insert into PRODUCT (title, price) values ('Vinegar - Red Wine', 79.88);
insert into PRODUCT (title, price) values ('Ostrich - Prime Cut', 92.16);
insert into PRODUCT (title, price) values ('Brandy Cherry - Mcguinness', 25.19);
insert into PRODUCT (title, price) values ('Chinese Foods - Thick Noodles', 37.83);
insert into PRODUCT (title, price) values ('Soup - Campbells Broccoli', 40.19);
insert into PRODUCT (title, price) values ('Catfish - Fillets', 81.22);
insert into PRODUCT (title, price) values ('Bouq All Italian - Primerba', 27.49);
insert into PRODUCT (title, price) values ('Soup - Campbells Chili', 63.35);
insert into PRODUCT (title, price) values ('Chicken - Bones', 65.85);
insert into PRODUCT (title, price) values ('Pasta - Agnolotti - Butternut', 11.9);
insert into PRODUCT (title, price) values ('Appetizer - Cheese Bites', 84.89);
insert into PRODUCT (title, price) values ('Crackers - Trio', 57.69);
insert into PRODUCT (title, price) values ('Beef - Diced', 46.81);
insert into PRODUCT (title, price) values ('Red Cod Fillets - 225g', 69.63);
insert into PRODUCT (title, price) values ('Wine - White, Cooking', 60.98);
insert into PRODUCT (title, price) values ('Lid - Translucent, 3.5 And 6 Oz', 93.7);
insert into PRODUCT (title, price) values ('Juice - Pineapple, 48 Oz', 40.5);
insert into PRODUCT (title, price) values ('Greens Mustard', 82.21);
insert into PRODUCT (title, price) values ('Soupcontfoam16oz 116con', 44.82);
insert into PRODUCT (title, price) values ('Potatoes - Yukon Gold, 80 Ct', 90.64);
insert into PRODUCT (title, price) values ('Chicken - Leg / Back Attach', 29.11);
insert into PRODUCT (title, price) values ('Soap - Pine Sol Floor Cleaner', 99.38);
insert into PRODUCT (title, price) values ('Jameson - Irish Whiskey', 51.41);
insert into PRODUCT (title, price) values ('Bread - Rosemary Focaccia', 42.54);
insert into PRODUCT (title, price) values ('Bagels Poppyseed', 25.62);
insert into PRODUCT (title, price) values ('Pickerel - Fillets', 86.01);
insert into PRODUCT (title, price) values ('Carbonated Water - Blackberry', 11.22);
insert into PRODUCT (title, price) values ('Cheese Cheddar Processed', 15.28);
insert into PRODUCT (title, price) values ('Food Colouring - Green', 37.95);
insert into PRODUCT (title, price) values ('Veal - Insides, Grains', 73.9);
insert into PRODUCT (title, price) values ('Beef - Eye Of Round', 26.36);
insert into PRODUCT (title, price) values ('Nut - Chestnuts, Whole', 95.44);
insert into PRODUCT (title, price) values ('Sauce - Fish 25 Ozf Bottle', 92.33);
insert into PRODUCT (title, price) values ('Crackers - Trio', 42.47);
insert into PRODUCT (title, price) values ('Basil - Seedlings Cookstown', 61.26);
insert into PRODUCT (title, price) values ('Vodka - Smirnoff', 70.52);
insert into PRODUCT (title, price) values ('Olives - Kalamata', 17.77);
insert into PRODUCT (title, price) values ('Foil Cont Round', 69.09);
insert into PRODUCT (title, price) values ('Lamb - Whole Head Off,nz', 41.72);
insert into PRODUCT (title, price) values ('Cake - Mini Potato Pancake', 97.09);
insert into PRODUCT (title, price) values ('Grenadillo', 63.42);
insert into PRODUCT (title, price) values ('Soup Campbells - Tomato Bisque', 99.71);
insert into PRODUCT (title, price) values ('Water - Evian 355 Ml', 29.02);
insert into PRODUCT (title, price) values ('Seedlings - Mix, Organic', 82.52);
insert into PRODUCT (title, price) values ('Wine - George Duboeuf Rose', 80.79);
insert into PRODUCT (title, price) values ('Wine - Two Oceans Sauvignon', 65.78);
insert into PRODUCT (title, price) values ('Puree - Guava', 71.64);
insert into PRODUCT (title, price) values ('Beef - Top Butt', 49.94);
insert into PRODUCT (title, price) values ('Ice Cream Bar - Hageen Daz To', 97.59);
insert into PRODUCT (title, price) values ('Bread Foccacia Whole', 80.16);
insert into PRODUCT (title, price) values ('Spice - Chili Powder Mexican', 80.95);
insert into PRODUCT (title, price) values ('Pepper - Black, Crushed', 52.97);
insert into PRODUCT (title, price) values ('Muffin - Carrot Individual Wrap', 42.58);
insert into PRODUCT (title, price) values ('Stock - Fish', 51.0);
insert into PRODUCT (title, price) values ('Sprouts Dikon', 98.22);
insert into PRODUCT (title, price) values ('Rice Pilaf, Dry,package', 27.64);
insert into PRODUCT (title, price) values ('Salmon - Canned', 33.87);
insert into PRODUCT (title, price) values ('Cloves - Whole', 42.22);
insert into PRODUCT (title, price) values ('Bagels Poppyseed', 64.52);
insert into PRODUCT (title, price) values ('Milk - 1%', 30.23);
insert into PRODUCT (title, price) values ('Sage - Ground', 56.69);
insert into PRODUCT (title, price) values ('Chinese Foods - Cantonese', 68.52);
insert into PRODUCT (title, price) values ('Tomatoes Tear Drop', 39.98);
insert into PRODUCT (title, price) values ('Foam Tray S2', 54.5);
insert into PRODUCT (title, price) values ('Sprouts - Peppercress', 36.98);
insert into PRODUCT (title, price) values ('Lobster - Base', 44.54);
insert into PRODUCT (title, price) values ('Ecolab - Hobart Upr Prewash Arm', 49.99);
insert into PRODUCT (title, price) values ('Glass Clear 8 Oz', 82.33);
insert into PRODUCT (title, price) values ('Green Scrubbie Pad H.duty', 76.19);
insert into PRODUCT (title, price) values ('Beer - Muskoka Cream Ale', 29.41);
insert into PRODUCT (title, price) values ('Sambuca Cream', 41.22);
insert into PRODUCT (title, price) values ('Placemat - Scallop, White', 22.84);
insert into PRODUCT (title, price) values ('Jagermeister', 22.03);
insert into PRODUCT (title, price) values ('Table Cloth 54x72 Colour', 77.77);
insert into PRODUCT (title, price) values ('French Pastry - Mini Chocolate', 34.7);
insert into PRODUCT (title, price) values ('Dates', 90.61);
insert into PRODUCT (title, price) values ('Cake - Cake Sheet Macaroon', 61.15);
insert into PRODUCT (title, price) values ('Wine - Red, Concha Y Toro', 11.25);
insert into PRODUCT (title, price) values ('Flour Dark Rye', 93.8);
insert into PRODUCT (title, price) values ('Pastry - Butterscotch Baked', 68.17);
insert into PRODUCT (title, price) values ('Chicken - Whole Roasting', 62.45);
insert into PRODUCT (title, price) values ('Wine - Vouvray Cuvee Domaine', 81.56);
insert into PRODUCT (title, price) values ('Cheese - Le Cheve Noir', 59.5);
insert into PRODUCT (title, price) values ('Wine - White, Gewurtzraminer', 53.14);
insert into PRODUCT (title, price) values ('Limes', 74.95);
insert into PRODUCT (title, price) values ('Cheese - St. Paulin', 72.4);
insert into PRODUCT (title, price) values ('Wine - Tribal Sauvignon', 25.44);
insert into PRODUCT (title, price) values ('Gin - Gilbeys London, Dry', 35.31);
insert into PRODUCT (title, price) values ('Liners - Baking Cups', 49.76);
insert into PRODUCT (title, price) values ('Lid - High Heat, Super Clear', 69.67);
insert into PRODUCT (title, price) values ('Bread - Bistro White', 91.46);
insert into PRODUCT (title, price) values ('Dill Weed - Dry', 34.51);
insert into PRODUCT (title, price) values ('Arizona - Plum Green Tea', 21.49);
insert into PRODUCT (title, price) values ('Scallops 60/80 Iqf', 78.59);
insert into PRODUCT (title, price) values ('Potatoes - Mini White 3 Oz', 99.81);
insert into PRODUCT (title, price) values ('Salt - Table', 64.45);
insert into PRODUCT (title, price) values ('Tart - Lemon', 36.88);
insert into PRODUCT (title, price) values ('Spaghetti Squash', 50.8);
insert into PRODUCT (title, price) values ('Wine - Red, Gamay Noir', 86.65);
insert into PRODUCT (title, price) values ('Cheese - Romano, Grated', 97.35);
insert into PRODUCT (title, price) values ('Creme De Banane - Marie', 41.96);
insert into PRODUCT (title, price) values ('Veal - Striploin', 48.93);
insert into PRODUCT (title, price) values ('Persimmons', 18.93);
insert into PRODUCT (title, price) values ('Eggplant Oriental', 61.62);
insert into PRODUCT (title, price) values ('Seedlings - Clamshell', 18.62);
insert into PRODUCT (title, price) values ('Eggplant Italian', 85.77);
insert into PRODUCT (title, price) values ('Lettuce - Escarole', 31.16);
insert into PRODUCT (title, price) values ('Snapple - Iced Tea Peach', 23.8);
insert into PRODUCT (title, price) values ('Steam Pan Full Lid', 33.72);
insert into PRODUCT (title, price) values ('Pop Shoppe Cream Soda', 34.78);
insert into PRODUCT (title, price) values ('Yogurt - Cherry, 175 Gr', 40.54);
insert into PRODUCT (title, price) values ('Mushrooms - Honey', 85.18);
insert into PRODUCT (title, price) values ('Carbonated Water - Strawberry', 30.2);
insert into PRODUCT (title, price) values ('Water - Aquafina Vitamin', 43.73);
insert into PRODUCT (title, price) values ('Soup Campbells Mexicali Tortilla', 27.19);
insert into PRODUCT (title, price) values ('Tofu - Firm', 21.01);
insert into PRODUCT (title, price) values ('Numi - Assorted Teas', 73.37);
insert into PRODUCT (title, price) values ('Ecolab - Ster Bac', 43.91);
insert into PRODUCT (title, price) values ('Sour Puss - Tangerine', 81.16);
insert into PRODUCT (title, price) values ('Cookies - Fortune', 87.02);
insert into PRODUCT (title, price) values ('Dill - Primerba, Paste', 96.57);
insert into PRODUCT (title, price) values ('Beer - Rickards Red', 71.27);
insert into PRODUCT (title, price) values ('Foil Wrap', 67.75);
insert into PRODUCT (title, price) values ('Vanilla Beans', 52.19);
insert into PRODUCT (title, price) values ('Spice - Pepper Portions', 99.71);
insert into PRODUCT (title, price) values ('Wine - Clavet Saint Emilion', 82.65);
insert into PRODUCT (title, price) values ('Chinese Foods - Cantonese', 90.25);
insert into PRODUCT (title, price) values ('Nut - Macadamia', 26.22);
insert into PRODUCT (title, price) values ('Sandwich Wrap', 79.96);
insert into PRODUCT (title, price) values ('Mix - Cocktail Ice Cream', 10.87);
insert into PRODUCT (title, price) values ('Papadam', 83.15);
insert into PRODUCT (title, price) values ('Lamb - Whole, Fresh', 69.38);
insert into PRODUCT (title, price) values ('Passion Fruit', 68.43);
insert into PRODUCT (title, price) values ('Sole - Dover, Whole, Fresh', 23.39);
insert into PRODUCT (title, price) values ('Longos - Assorted Sandwich', 76.1);
insert into PRODUCT (title, price) values ('Cornflakes', 92.55);
insert into PRODUCT (title, price) values ('Sole - Dover, Whole, Fresh', 33.4);
insert into PRODUCT (title, price) values ('Milk - Chocolate 500ml', 26.7);
insert into PRODUCT (title, price) values ('True - Vue Containers', 41.77);
insert into PRODUCT (title, price) values ('Jolt Cola - Electric Blue', 93.11);
insert into PRODUCT (title, price) values ('Cheese - Cottage Cheese', 47.63);
insert into PRODUCT (title, price) values ('Veal - Leg, Provimi - 50 Lb Max', 78.58);
insert into PRODUCT (title, price) values ('Sugar - Cubes', 93.32);
insert into PRODUCT (title, price) values ('Juice Peach Nectar', 70.16);
insert into PRODUCT (title, price) values ('Chips Potato All Dressed - 43g', 90.02);
insert into PRODUCT (title, price) values ('Beans - Kidney, Canned', 29.37);
insert into PRODUCT (title, price) values ('Eggplant - Asian', 80.48);
insert into PRODUCT (title, price) values ('Asparagus - Mexican', 65.05);
insert into PRODUCT (title, price) values ('Onions - White', 89.94);
insert into PRODUCT (title, price) values ('Wine - Penfolds Koonuga Hill', 45.65);
insert into PRODUCT (title, price) values ('Melon - Watermelon Yellow', 51.12);
insert into PRODUCT (title, price) values ('Kirsch - Schloss', 98.9);
insert into PRODUCT (title, price) values ('Doilies - 7, Paper', 74.17);
insert into PRODUCT (title, price) values ('Coffee - Hazelnut Cream', 16.9);
insert into PRODUCT (title, price) values ('Chocolate - Dark', 28.02);
insert into PRODUCT (title, price) values ('Lettuce - Treviso', 60.83);
insert into PRODUCT (title, price) values ('Bread - Bistro Sour', 49.33);
insert into PRODUCT (title, price) values ('Cookies Cereal Nut', 20.77);
insert into PRODUCT (title, price) values ('Mcgillicuddy Vanilla Schnap', 58.89);
insert into PRODUCT (title, price) values ('Smoked Paprika', 65.05);
insert into PRODUCT (title, price) values ('Sauce - Salsa', 65.84);
insert into PRODUCT (title, price) values ('Tuna - Bluefin', 53.0);
insert into PRODUCT (title, price) values ('Wine - Pinot Grigio Collavini', 55.75);
insert into PRODUCT (title, price) values ('Cookies Oatmeal Raisin', 55.46);
insert into PRODUCT (title, price) values ('Chips Potato Swt Chilli Sour', 24.42);
insert into PRODUCT (title, price) values ('Wine - Magnotta - Belpaese', 18.3);
insert into PRODUCT (title, price) values ('Beef - Tenderloin - Aa', 64.3);
insert into PRODUCT (title, price) values ('Fond - Chocolate', 81.63);
insert into PRODUCT (title, price) values ('Yoplait - Strawbrasp Peac', 53.78);
insert into PRODUCT (title, price) values ('Food Colouring - Orange', 78.29);
insert into PRODUCT (title, price) values ('Cheese - Sheep Milk', 90.5);
insert into PRODUCT (title, price) values ('Tuna - Canned, Flaked, Light', 64.22);
insert into PRODUCT (title, price) values ('Lime Cordial - Roses', 80.12);
insert into PRODUCT (title, price) values ('Bagel - 12 Grain Preslice', 77.87);
insert into PRODUCT (title, price) values ('Soup - French Can Pea', 35.43);
insert into PRODUCT (title, price) values ('Beef - Bones, Marrow', 92.98);
insert into PRODUCT (title, price) values ('Madeira', 32.5);
insert into PRODUCT (title, price) values ('Anchovy In Oil', 15.44);
insert into PRODUCT (title, price) values ('Bread - Sticks, Thin, Plain', 25.44);
insert into PRODUCT (title, price) values ('Cake - French Pear Tart', 85.39);
insert into PRODUCT (title, price) values ('Basil - Thai', 49.96);
insert into PRODUCT (title, price) values ('Cheese - Roquefort Pappillon', 90.21);
insert into PRODUCT (title, price) values ('Pimento - Canned', 11.96);
insert into PRODUCT (title, price) values ('Veal - Leg', 30.36);
insert into PRODUCT (title, price) values ('Lettuce - Spring Mix', 40.78);
insert into PRODUCT (title, price) values ('Slt - Individual Portions', 28.18);
insert into PRODUCT (title, price) values ('Mushroom Morel Fresh', 51.36);
insert into PRODUCT (title, price) values ('Appetizer - Cheese Bites', 14.41);
insert into PRODUCT (title, price) values ('Lettuce - Lolla Rosa', 75.32);
insert into PRODUCT (title, price) values ('Kiwano', 49.61);
insert into PRODUCT (title, price) values ('Ecolab - Power Fusion', 97.05);
insert into PRODUCT (title, price) values ('Bagel - Plain', 63.21);
insert into PRODUCT (title, price) values ('Puree - Raspberry', 69.88);
insert into PRODUCT (title, price) values ('Spic And Span All Purpose', 37.54);
insert into PRODUCT (title, price) values ('Ecolab - Orange Frc, Cleaner', 59.17);
insert into PRODUCT (title, price) values ('Bread - Corn Muffaletta', 91.13);
insert into PRODUCT (title, price) values ('Pasta - Lasagna Noodle, Frozen', 97.07);
insert into PRODUCT (title, price) values ('Cheese Cloth', 46.05);
insert into PRODUCT (title, price) values ('Pepper - Green', 99.85);
insert into PRODUCT (title, price) values ('Hinge W Undercut', 41.57);
insert into PRODUCT (title, price) values ('Mushrooms - Black, Dried', 20.13);
insert into PRODUCT (title, price) values ('Carbonated Water - Peach', 55.74);
insert into PRODUCT (title, price) values ('Shrimp - 100 / 200 Cold Water', 86.19);
insert into PRODUCT (title, price) values ('Trueblue - Blueberry Cranberry', 42.5);
insert into PRODUCT (title, price) values ('Thermometer Digital', 26.61);
insert into PRODUCT (title, price) values ('Anchovy Fillets', 12.68);
insert into PRODUCT (title, price) values ('Grapes - Red', 99.72);
insert into PRODUCT (title, price) values ('Pork - Smoked Kassler', 16.18);
insert into PRODUCT (title, price) values ('Tuna - Bluefin', 52.03);
insert into PRODUCT (title, price) values ('Sloe Gin - Mcguinness', 98.8);
insert into PRODUCT (title, price) values ('Chicken - White Meat, No Tender', 35.97);
insert into PRODUCT (title, price) values ('Bread - Corn Muffaleta Onion', 80.63);
insert into PRODUCT (title, price) values ('Pasta - Lasagna, Dry', 31.16);
insert into PRODUCT (title, price) values ('Sole - Fillet', 24.43);
insert into PRODUCT (title, price) values ('Bread Crumbs - Panko', 81.22);
insert into PRODUCT (title, price) values ('Bread - Corn Muffaletta', 24.99);
insert into PRODUCT (title, price) values ('Syrup - Monin, Swiss Choclate', 95.4);
insert into PRODUCT (title, price) values ('Coffee Cup 16oz Foam', 44.5);
insert into PRODUCT (title, price) values ('Cloves - Whole', 17.06);
insert into PRODUCT (title, price) values ('Onions - Red Pearl', 41.33);
insert into PRODUCT (title, price) values ('Bread - Dark Rye, Loaf', 85.24);
insert into PRODUCT (title, price) values ('Sprouts - Alfalfa', 13.53);
insert into PRODUCT (title, price) values ('Coffee Guatemala Dark', 80.02);
insert into PRODUCT (title, price) values ('Salt - Kosher', 42.96);
insert into PRODUCT (title, price) values ('Soda Water - Club Soda, 355 Ml', 79.48);
insert into PRODUCT (title, price) values ('Sage Ground Wiberg', 88.89);
insert into PRODUCT (title, price) values ('Chips Potato All Dressed - 43g', 37.61);
insert into PRODUCT (title, price) values ('Quiche Assorted', 10.48);
insert into PRODUCT (title, price) values ('Tart - Lemon', 29.64);
insert into PRODUCT (title, price) values ('Lychee', 41.91);
insert into PRODUCT (title, price) values ('Beef - Prime Rib Aaa', 48.39);
insert into PRODUCT (title, price) values ('Coffee - Ristretto Coffee Capsule', 33.74);
insert into PRODUCT (title, price) values ('Crab Brie In Phyllo', 84.88);
insert into PRODUCT (title, price) values ('Sponge Cake Mix - Vanilla', 12.58);
insert into PRODUCT (title, price) values ('Bread Crumbs - Japanese Style', 93.16);
insert into PRODUCT (title, price) values ('Turnip - Wax', 24.92);
insert into PRODUCT (title, price) values ('Carbonated Water - Lemon Lime', 20.48);
insert into PRODUCT (title, price) values ('Wine - Gato Negro Cabernet', 43.82);
insert into PRODUCT (title, price) values ('Bread - Rye', 95.83);
insert into PRODUCT (title, price) values ('Compound - Mocha', 83.79);
insert into PRODUCT (title, price) values ('Kahlua', 66.16);
insert into PRODUCT (title, price) values ('Spice - Pepper Portions', 71.84);
insert into PRODUCT (title, price) values ('Bacardi Raspberry', 97.46);
insert into PRODUCT (title, price) values ('Persimmons', 48.58);
insert into PRODUCT (title, price) values ('Vol Au Vents', 45.23);
insert into PRODUCT (title, price) values ('Zucchini - Mini, Green', 41.91);
insert into PRODUCT (title, price) values ('Cookies - Amaretto', 10.97);
insert into PRODUCT (title, price) values ('Pasta - Canelloni, Single Serve', 48.29);
insert into PRODUCT (title, price) values ('Milk Powder', 54.83);
insert into PRODUCT (title, price) values ('Quiche Assorted', 24.8);
insert into PRODUCT (title, price) values ('Lettuce - Green Leaf', 35.46);
insert into PRODUCT (title, price) values ('Lamb - Whole, Frozen', 57.47);
insert into PRODUCT (title, price) values ('Crush - Grape, 355 Ml', 15.62);
insert into PRODUCT (title, price) values ('Bread - Multigrain Oval', 39.28);
insert into PRODUCT (title, price) values ('Energy Drink Red Bull', 65.21);
insert into PRODUCT (title, price) values ('Tamarillo', 26.09);
insert into PRODUCT (title, price) values ('Soup - Knorr, Country Bean', 92.71);
insert into PRODUCT (title, price) values ('Salt - Table', 83.44);
insert into PRODUCT (title, price) values ('Cheese - Montery Jack', 34.91);
insert into PRODUCT (title, price) values ('Oil - Shortening - All - Purpose', 20.91);
insert into PRODUCT (title, price) values ('Praline Paste', 78.19);
insert into PRODUCT (title, price) values ('Ginger - Pickled', 28.56);
insert into PRODUCT (title, price) values ('Cheese - Parmigiano Reggiano', 31.6);
insert into PRODUCT (title, price) values ('Lobster - Canned Premium', 44.55);
insert into PRODUCT (title, price) values ('Tomatoes - Orange', 69.05);
insert into PRODUCT (title, price) values ('Cheese - Augre Des Champs', 61.82);
insert into PRODUCT (title, price) values ('Pasta - Fusili, Dry', 32.46);
insert into PRODUCT (title, price) values ('Saskatoon Berries - Frozen', 89.09);
insert into PRODUCT (title, price) values ('Coffee - Ristretto Coffee Capsule', 24.15);
insert into PRODUCT (title, price) values ('Table Cloth 62x114 White', 67.43);
insert into PRODUCT (title, price) values ('Kirsch - Schloss', 64.23);
insert into PRODUCT (title, price) values ('Smirnoff Green Apple Twist', 34.7);
insert into PRODUCT (title, price) values ('Muffin Orange Individual', 47.74);
insert into PRODUCT (title, price) values ('Pork - Backs - Boneless', 83.09);
insert into PRODUCT (title, price) values ('Wine - Riesling Alsace Ac 2001', 90.24);
insert into PRODUCT (title, price) values ('Chicken - Base', 62.99);
insert into PRODUCT (title, price) values ('Praline Paste', 44.93);
insert into PRODUCT (title, price) values ('Tobasco Sauce', 48.86);
insert into PRODUCT (title, price) values ('Juice - Prune', 38.67);
insert into PRODUCT (title, price) values ('Sobe - Tropical Energy', 17.37);
insert into PRODUCT (title, price) values ('Squash - Pattypan, Yellow', 31.26);
insert into PRODUCT (title, price) values ('Tomatoes', 59.38);
insert into PRODUCT (title, price) values ('Kellogs Special K Cereal', 58.5);
insert into PRODUCT (title, price) values ('Wine - Chianti Classica Docg', 61.11);
insert into PRODUCT (title, price) values ('Sour Cream', 11.84);
insert into PRODUCT (title, price) values ('Numi - Assorted Teas', 12.52);
insert into PRODUCT (title, price) values ('Nut - Pecan, Halves', 73.01);
insert into PRODUCT (title, price) values ('Quail - Whole, Bone - In', 75.82);
insert into PRODUCT (title, price) values ('Cheese - St. Paulin', 86.04);
insert into PRODUCT (title, price) values ('Zucchini - Green', 93.75);
insert into PRODUCT (title, price) values ('Wine - Rosso Del Veronese Igt', 93.61);
insert into PRODUCT (title, price) values ('Aspic - Amber', 17.75);
insert into PRODUCT (title, price) values ('Appetizer - Spring Roll, Veg', 11.18);
insert into PRODUCT (title, price) values ('Dill Weed - Fresh', 39.7);
insert into PRODUCT (title, price) values ('Spice - Onion Powder Granulated', 35.84);
insert into PRODUCT (title, price) values ('Wine - Red, Mosaic Zweigelt', 10.91);
insert into PRODUCT (title, price) values ('Nestea - Ice Tea, Diet', 90.06);
insert into PRODUCT (title, price) values ('Langers - Cranberry Cocktail', 22.07);
